// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  textbookSidebar: [
    {
      type: 'category',
      label: 'Introduction to Physical AI & Humanoid Robotics',
      link: {
        type: 'generated-index',
        title: 'Introduction',
        description: 'An overview of Physical AI, Embodied Intelligence, and Humanoid Robotics.',
        slug: '/category/introduction',
      },
      items: [
        'introduction/overview',
        'introduction/physical-ai-concept',
        'introduction/embodied-intelligence',
        'introduction/learning-outcomes',
        'introduction/why-humanoids',
        'introduction/assessment-lab',
        'introduction/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Setup Guides',
      link: {
        type: 'generated-index',
        title: 'Setup Guides',
        description: 'Learn how to set up your development environment for Physical AI and Humanoid Robotics.',
        slug: '/category/setup-guides',
      },
      items: [
        {type: 'autogenerated', dirName: 'setup-guides'},
        'hardware/robots',
      ],
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2 (Weeks 3–5)',
      link: {
        type: 'generated-index',
        title: 'Module 1: ROS 2',
        description: 'Explore the Robot Operating System 2 for robotics development.',
        slug: '/category/module-1-ros2',
      },
      items: [{type: 'autogenerated', dirName: 'modules/module-1-ros2'}],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin (Weeks 6–7)',
      link: {
        type: 'generated-index',
        title: 'Module 2: Digital Twin',
        description: 'Dive into the world of digital twins for robotics simulation.',
        slug: '/category/module-2-digital-twin',
      },
      items: [{type: 'autogenerated', dirName: 'modules/module-2-digital-twin'}],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac (Weeks 8–10)',
      link: {
        type: 'generated-index',
        title: 'Module 3: NVIDIA Isaac',
        description: 'Learn about NVIDIA Isaac Sim for advanced robotics simulation.',
        slug: '/category/module-3-isaac-sim',
      },
      items: [{type: 'autogenerated', dirName: 'modules/module-3-isaac'}],
    },
    {
      type: 'category',
      label: 'Module 4: VLA & Humanoids (Weeks 11–13)',
      link: {
        type: 'generated-index',
        title: 'Module 4: VLA & Humanoids',
        description: 'Understand Visual Language Models (VLA) and their application to humanoids.',
        slug: '/category/module-4-vla-humanoids',
      },
      items: [{type: 'autogenerated', dirName: 'modules/module-4-vla-humanoids'}],
    },
    'references', // Generated in T048-T050
  ],
};

export default sidebars;